name: Homebrew CI (macOS)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    env:
      HOMEBREW_NO_ANALYTICS: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show brew config
        run: |
          set -euxo pipefail
          brew --version
          brew config

      - name: Create local tap and install (HEAD)
        run: |
          set -euxo pipefail
          TAP="local/git-branches"
          brew tap-new "$TAP"
          TAP_DIR="$(brew --repo "$TAP")"
          mkdir -p "$TAP_DIR/Formula"
          cp Formula/git-branches.rb "$TAP_DIR/Formula/"
          brew install --build-from-source --HEAD "$TAP/git-branches"

      - name: Smoke test
        run: |
          set -euxo pipefail
          git-branches -h || true
          which git-branches
          git-branches -h | head -n 5
